// <auto-generated />
using Gambl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gambl.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241213133526_InitialCreate4")]
    partial class InitialCreate4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Gambl.Models.CourseBuy", b =>
                {
                    b.Property<int>("CourseSignUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseSignUpId");

                    b.ToTable("CourseBuys");
                });

            modelBuilder.Entity("Gambl.Models.CourseInfo", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseExplain")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseInstructor")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("CourseInfos");
                });

            modelBuilder.Entity("Gambl.Models.InstructorInfo", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstructorEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorFN")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorLN")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("InstructorId");

                    b.ToTable("InstructorInfos");
                });

            modelBuilder.Entity("Gambl.Models.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserFN")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserLN")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
